name = input("შეიყვანეთ თქვენი სახელი: ")
surname = input("შეიყვანეთ თქვენი გვარი: ")
age = input(("შეიყვანეთ თქვენი ასაკი: "))
height = input(("შეიყვანეთ თქვენი სიმაღლე (მეტრებში): "))
weight = input(("შეიყვანეთ თქვენი წონა (კილოგრამებში): "))

სახელი = ("სახელი: ")
გვარი = ("გვარი: ")
ასაკი = ("ასაკი: ")
სიმაღლე = ("სიმაღლე: ")
წონა = ("წონა: ")
concatenated = name + surname + " " + age + height + weight 
print("შედეგი:") 
print("სახელი: " , name) 
print("გვარი: " , surname) 
print("ასაკი: " , age) 
print("სიმაღლე: " , height) 
print("წონა: " , weight) 